"""
Data models that flow through the Argus-AI loop.

A Finding is born in Discovery, gains a verdict in Validation, gains a
remediation in Patch Proposal, and is re-checked in Re-scan. Keeping the
state on one object makes the closed loop auditable end to end.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any


class Severity(str, Enum):
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    INFO = "Info"


class ValidationVerdict(str, Enum):
    CONFIRMED = "confirmed"          # proof-of-exploit succeeded in sandbox
    UNCONFIRMED = "unconfirmed"      # could not be reproduced — treated as possible hallucination
    SKIPPED = "skipped"              # validation disabled / out of scope


class PatchStatus(str, Enum):
    PROPOSED = "proposed"
    APPLIED = "applied"
    REJECTED = "rejected"
    NOT_APPLICABLE = "n/a"


@dataclass
class Command:
    """A single tool invocation generated by the executor model."""

    rationale: str          # why this command (explainability)
    command: str            # the literal shell command
    phase: str              # PTES phase: recon / scan / vuln-id / exploit / post-exploit
    stdout: str = ""
    stderr: str = ""
    exit_code: int | None = None


@dataclass
class Finding:
    """A candidate vulnerability and everything learned about it across the loop."""

    target: str
    title: str
    description: str
    severity: Severity = Severity.INFO
    phase: str = "vuln-id"
    discovery_commands: list[Command] = field(default_factory=list)

    # Filled by Validation
    verdict: ValidationVerdict = ValidationVerdict.UNCONFIRMED
    proof: str = ""                 # the evidence string from the sandbox

    # Filled by Patch Proposal
    patch_status: PatchStatus = PatchStatus.NOT_APPLICABLE
    remediation: str = ""           # structured fix from the advisor model

    # Filled by Re-scan
    resolved_after_patch: bool | None = None

    finding_id: str = field(default_factory=lambda: f"F-{int(time.time()*1000)%100000:05d}")

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["severity"] = self.severity.value
        d["verdict"] = self.verdict.value
        d["patch_status"] = self.patch_status.value
        return d


@dataclass
class LoopResult:
    """Outcome of one full Discovery→Validation→Patch→Re-scan iteration."""

    iteration: int
    findings: list[Finding] = field(default_factory=list)
    confirmed_count: int = 0
    patched_count: int = 0
    resolved_count: int = 0

    def summary(self) -> str:
        return (f"Iteration {self.iteration}: {len(self.findings)} findings, "
                f"{self.confirmed_count} confirmed, {self.patched_count} patched, "
                f"{self.resolved_count} verified resolved.")
